// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Question struct {
	Questionid   int64
	Title        string
	Titleslug    string
	Difficulty   string
	Functionname string
	Content      string
	Codesnippets string
	Testcases    string
}

type Submission struct {
	ID         int64
	Questionid int64
	Langslug   string
	Solved     int64
}
