// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Question struct {
	QuestionID   int64
	Title        string
	TitleSlug    string
	Difficulty   string
	FunctionName string
	Content      string
	CodeSnippets string
	TestCases    string
	CreatedAt    string
}

type Submission struct {
	ID            int64
	QuestionID    int64
	LangSlug      string
	Solved        int64
	LastAttempted string
}
