// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Question struct {
	QuestionID   int64
	Title        string
	TitleSlug    string
	Difficulty   string
	FunctionName string
	Content      string
	CodeSnippets string
	TestCases    string
	CreatedAt    string
	SubmitID     sql.NullInt64
	PaidOnly     int64
}

type Submission struct {
	ID             int64
	QuestionID     int64
	LangSlug       string
	Solved         int64
	LastAttempted  string
	FailedAttempts int64
	TimesSolved    int64
}
